let a;
let date;
let time;
setInterval(() => {
a = new Date();
date = a.toLocaleDateString();
document.getElementById('date').innerHTML = date;
time = a.getHours() + ':' + a.getMinutes() + ':' + a.getSeconds();
document.getElementById('time').innerHTML = time;
// var utcTime = a.getTime() + (a.getTimezoneOffset() * 60000);
// var timeOffset = 5.5;
// var IndianTime = new Date(utcTime + (360000 * timeOffset));
var utcTime = a.getTime() + (a.getTimezoneOffset() * 60000);
var timeOffset = 12;
var NewZealandTime = new Date(utcTime + (3600000 * timeOffset));
document.getElementById('Nztime').innerHTML = NewZealandTime;
var utcTime = a.getTime() + (a.getTimezoneOffset() * 60000);
var timeOffset = 1;
var EnglandTime = new Date(utcTime + (3600000 * timeOffset));   
document.getElementById('Engtime').innerHTML = EnglandTime;
var utcTime = a.getTime() + (a.getTimezoneOffset() * 60000);
var timeOffset = 2;
var SaTime = new Date(utcTime + (3600000 * timeOffset)); 
document.getElementById('Satime').innerHTML = SaTime;
}, 1000);